export const getPagesData = [
  {
    pageName: "@BollywoodBuzz",
    category: "Bollywood",
    followers: 120000,
    profileLink: "https://instagram.com/BollywoodBuzz",
    posts: [
      {
        postLink: "https://link.com/post1",
        type: "Reel",
        likes: 4500,
        views: 9000,
        shares: 150,
        comments: 300,
        reach: 12000,
        impressions: 15000,
      },
      {
        postLink: "https://link.com/post2",
        type: "Static",
        likes: 2000,
        views: 5000,
        shares: 100,
        comments: 120,
        reach: 7000,
        impressions: 9000,
      },
    ],
  },
  {
    pageName: "@MemeMaster",
    category: "Meme",
    followers: 250000,
    profileLink: "https://instagram.com/MemeMaster",
    posts: [
      {
        postLink: "https://link.com/meme1",
        type: "Static",
        likes: 3500,
        views: 8000,
        shares: 200,
        comments: 220,
        reach: 10000,
        impressions: 13000,
      },
    ],
  },
  {
    pageName: "@TravelTales",
    category: "Travel",
    followers: 180000,
    profileLink: "https://instagram.com/TravelTales",
    posts: [
      {
        postLink: "https://link.com/travel1",
        type: "Reel",
        likes: 6700,
        views: 14000,
        shares: 400,
        comments: 520,
        reach: 17000,
        impressions: 21000,
      },
    ],
  },
  {
    pageName: "@FoodieFiesta",
    category: "Food",
    followers: 95000,
    profileLink: "https://instagram.com/FoodieFiesta",
    posts: [
      {
        postLink: "https://link.com/food1",
        type: "Static",
        likes: 2300,
        views: 4000,
        shares: 90,
        comments: 130,
        reach: 5000,
        impressions: 7500,
      },
    ],
  },
  {
    pageName: "@TechTricks",
    category: "Technology",
    followers: 320000,
    profileLink: "https://instagram.com/TechTricks",
    posts: [
      {
        postLink: "https://link.com/tech1",
        type: "Reel",
        likes: 8000,
        views: 16000,
        shares: 500,
        comments: 600,
        reach: 20000,
        impressions: 25000,
      },
    ],
  },
  {
    pageName: "@FashionFrenzy",
    category: "Fashion",
    followers: 210000,
    profileLink: "https://instagram.com/FashionFrenzy",
    posts: [
      {
        postLink: "https://link.com/fashion1",
        type: "Static",
        likes: 4000,
        views: 7000,
        shares: 130,
        comments: 200,
        reach: 9000,
        impressions: 11000,
      },
    ],
  },
  {
    pageName: "@GamingGlitch",
    category: "Gaming",
    followers: 280000,
    profileLink: "https://instagram.com/GamingGlitch",
    posts: [
      {
        postLink: "https://link.com/game1",
        type: "Reel",
        likes: 9500,
        views: 18000,
        shares: 700,
        comments: 800,
        reach: 22000,
        impressions: 28000,
      },
    ],
  },
  {
    pageName: "@HealthHacks",
    category: "Health",
    followers: 87000,
    profileLink: "https://instagram.com/HealthHacks",
    posts: [
      {
        postLink: "https://link.com/health1",
        type: "Static",
        likes: 1900,
        views: 3000,
        shares: 70,
        comments: 90,
        reach: 4000,
        impressions: 5500,
      },
    ],
  },
  {
    pageName: "@CryptoCorner",
    category: "Finance",
    followers: 150000,
    profileLink: "https://instagram.com/CryptoCorner",
    posts: [
      {
        postLink: "https://link.com/crypto1",
        type: "Reel",
        likes: 5000,
        views: 10000,
        shares: 300,
        comments: 350,
        reach: 13000,
        impressions: 17000,
      },
    ],
  },
  {
    pageName: "@ComedyClub",
    category: "Comedy",
    followers: 400000,
    profileLink: "https://instagram.com/ComedyClub",
    posts: [
      {
        postLink: "https://link.com/comedy1",
        type: "Reel",
        likes: 12000,
        views: 22000,
        shares: 900,
        comments: 1100,
        reach: 27000,
        impressions: 35000,
      },
    ],
  },
  {
    pageName: "@PetParadise",
    category: "Pets",
    followers: 135000,
    profileLink: "https://instagram.com/PetParadise",
    posts: [
      {
        postLink: "https://link.com/pet1",
        type: "Static",
        likes: 3000,
        views: 5500,
        shares: 120,
        comments: 160,
        reach: 7000,
        impressions: 9000,
      },
    ],
  },
  {
    pageName: "@MusicMania",
    category: "Music",
    followers: 220000,
    profileLink: "https://instagram.com/MusicMania",
    posts: [
      {
        postLink: "https://link.com/music1",
        type: "Reel",
        likes: 7500,
        views: 14000,
        shares: 480,
        comments: 520,
        reach: 18000,
        impressions: 23000,
      },
    ],
  },
  {
    pageName: "@MotivationHub",
    category: "Motivation",
    followers: 99000,
    profileLink: "https://instagram.com/MotivationHub",
    posts: [
      {
        postLink: "https://link.com/motivation1",
        type: "Static",
        likes: 2500,
        views: 4000,
        shares: 100,
        comments: 140,
        reach: 5000,
        impressions: 6500,
      },
    ],
  },
  {
    pageName: "@ScienceSphere",
    category: "Education",
    followers: 175000,
    profileLink: "https://instagram.com/ScienceSphere",
    posts: [
      {
        postLink: "https://link.com/science1",
        type: "Reel",
        likes: 6800,
        views: 12000,
        shares: 350,
        comments: 400,
        reach: 15000,
        impressions: 19000,
      },
    ],
  },
  {
    pageName: "@ArtAttack",
    category: "Art",
    followers: 110000,
    profileLink: "https://instagram.com/ArtAttack",
    posts: [
      {
        postLink: "https://link.com/art1",
        type: "Static",
        likes: 2700,
        views: 4500,
        shares: 95,
        comments: 130,
        reach: 6000,
        impressions: 8000,
      },
    ],
  },
  {
    pageName: "@FitnessFreak",
    category: "Fitness",
    followers: 240000,
    profileLink: "https://instagram.com/FitnessFreak",
    posts: [
      {
        postLink: "https://link.com/fitness1",
        type: "Reel",
        likes: 8200,
        views: 16000,
        shares: 560,
        comments: 600,
        reach: 19000,
        impressions: 24000,
      },
    ],
  },
  {
    pageName: "@DIYDesigns",
    category: "DIY",
    followers: 92000,
    profileLink: "https://instagram.com/DIYDesigns",
    posts: [
      {
        postLink: "https://link.com/diy1",
        type: "Static",
        likes: 2100,
        views: 3700,
        shares: 80,
        comments: 110,
        reach: 4800,
        impressions: 6200,
      },
    ],
  },
  {
    pageName: "@MovieMantra",
    category: "Movies",
    followers: 195000,
    profileLink: "https://instagram.com/MovieMantra",
    posts: [
      {
        postLink: "https://link.com/movie1",
        type: "Reel",
        likes: 7000,
        views: 13000,
        shares: 420,
        comments: 500,
        reach: 16000,
        impressions: 21000,
      },
    ],
  },
  {
    pageName: "@BookBarn",
    category: "Books",
    followers: 85000,
    profileLink: "https://instagram.com/BookBarn",
    posts: [
      {
        postLink: "https://link.com/book1",
        type: "Static",
        likes: 1900,
        views: 3000,
        shares: 70,
        comments: 95,
        reach: 4000,
        impressions: 5500,
      },
    ],
  },
  {
    pageName: "@LuxuryLife",
    category: "Lifestyle",
    followers: 300000,
    profileLink: "https://instagram.com/LuxuryLife",
    posts: [
      {
        postLink: "https://link.com/luxury1",
        type: "Reel",
        likes: 10000,
        views: 20000,
        shares: 750,
        comments: 880,
        reach: 25000,
        impressions: 32000,
      },
    ],
  },
  {
    pageName: "@NewsNow",
    category: "News",
    followers: 275000,
    profileLink: "https://instagram.com/NewsNow",
    posts: [
      {
        postLink: "https://link.com/news1",
        type: "Static",
        likes: 5000,
        views: 9000,
        shares: 200,
        comments: 300,
        reach: 12000,
        impressions: 15000,
      },
    ],
  },
  {
    pageName: "@SportsSaga",
    category: "Sports",
    followers: 215000,
    profileLink: "https://instagram.com/SportsSaga",
    posts: [
      {
        postLink: "https://link.com/sport1",
        type: "Reel",
        likes: 8400,
        views: 17000,
        shares: 550,
        comments: 620,
        reach: 20000,
        impressions: 26000,
      },
    ],
  },
  {
    pageName: "@SpiritualSpace",
    category: "Spiritual",
    followers: 78000,
    profileLink: "https://instagram.com/SpiritualSpace",
    posts: [
      {
        postLink: "https://link.com/spiritual1",
        type: "Static",
        likes: 1600,
        views: 2800,
        shares: 60,
        comments: 80,
        reach: 3500,
        impressions: 5000,
      },
    ],
  },
  {
    pageName: "@HomeDecorHub",
    category: "Home Decor",
    followers: 120000,
    profileLink: "https://instagram.com/HomeDecorHub",
    posts: [
      {
        postLink: "https://link.com/decor1",
        type: "Static",
        likes: 2600,
        views: 4700,
        shares: 100,
        comments: 150,
        reach: 5500,
        impressions: 7000,
      },
    ],
  },
  {
    pageName: "@EntrepreneurEdge",
    category: "Business",
    followers: 330000,
    profileLink: "https://instagram.com/EntrepreneurEdge",
    posts: [
      {
        postLink: "https://link.com/business1",
        type: "Reel",
        likes: 9200,
        views: 19000,
        shares: 600,
        comments: 750,
        reach: 23000,
        impressions: 29000,
      },
    ],
  },
  {
    pageName: "@EcoEarth",
    category: "Environment",
    followers: 66000,
    profileLink: "https://instagram.com/EcoEarth",
    posts: [
      {
        postLink: "https://link.com/eco1",
        type: "Static",
        likes: 1400,
        views: 2500,
        shares: 55,
        comments: 75,
        reach: 3200,
        impressions: 4500,
      },
    ],
  },
  {
    pageName: "@StartupStories",
    category: "Startups",
    followers: 158000,
    profileLink: "https://instagram.com/StartupStories",
    posts: [
      {
        postLink: "https://link.com/startup1",
        type: "Reel",
        likes: 6100,
        views: 11000,
        shares: 340,
        comments: 410,
        reach: 14000,
        impressions: 18000,
      },
    ],
  },
  {
    pageName: "@DanceDynasty",
    category: "Dance",
    followers: 200000,
    profileLink: "https://instagram.com/DanceDynasty",
    posts: [
      {
        postLink: "https://link.com/dance1",
        type: "Reel",
        likes: 7300,
        views: 15000,
        shares: 500,
        comments: 590,
        reach: 18000,
        impressions: 23000,
      },
    ],
  },
  {
    pageName: "@WanderWorld",
    category: "Travel",
    followers: 175000,
    profileLink: "https://instagram.com/WanderWorld",
    posts: [
      {
        postLink: "https://link.com/wander1",
        type: "Static",
        likes: 2800,
        views: 5000,
        shares: 110,
        comments: 150,
        reach: 6500,
        impressions: 8000,
      },
    ],
  },
  {
    pageName: "@MindMatters",
    category: "Mental Health",
    followers: 89000,
    profileLink: "https://instagram.com/MindMatters",
    posts: [
      {
        postLink: "https://link.com/mind1",
        type: "Static",
        likes: 2000,
        views: 3500,
        shares: 85,
        comments: 110,
        reach: 4500,
        impressions: 6000,
      },
    ],
  },
];
